# Generated by Django 2.1.3 on 2018-11-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=50, verbose_name='合同名称')),
                ('date_signed', models.DateField(blank=True, null=True, verbose_name='签字日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('contract_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='合同编号')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('customer_type',
                 models.IntegerField(choices=[(1, '国内'), (2, '国际'), (99, '一般')], default=1, verbose_name='客户类型')),
                ('customer_code', models.CharField(max_length=5, verbose_name='客户代码')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='电子邮件')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('product_model', models.CharField(max_length=20, verbose_name='产品型号')),
                ('use_for', models.CharField(blank=True, max_length=30, null=True, verbose_name='用途')),
                ('product_size', models.CharField(blank=True, max_length=25, null=True, verbose_name='产品尺寸')),
                ('texture', models.CharField(max_length=30, verbose_name='材质')),
                ('volume_weight', models.FloatField(blank=True, null=True, verbose_name='容重')),
                ('piece_weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('order_quantity', models.IntegerField(blank=True, null=True, verbose_name='订单数量')),
                ('Customer',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Customer',
                                   verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50, verbose_name='工人姓名')),
                ('worker_type', models.CharField(
                    choices=[('01', '装窑工'), ('02', '烧窑工'), ('03', '成型工'), ('04', '拌料工'), ('05', '压砖工'), ('06', '切割工'),
                             ('07', '勤杂工'), ('08', '挤砖工'), ('99', '其他')], max_length=2, verbose_name='工人类型')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='其他说明')),
            ],
            options={
                'verbose_name': '工人',
                'verbose_name_plural': '工人',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Customer',
                                    verbose_name='签约客户'),
        ),
    ]
