# Generated by Django 2.1.3 on 2018-11-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('customer_code', models.CharField(max_length=5, verbose_name='Customer Code')),
                ('contact_name', models.CharField(max_length=20, verbose_name='Contact Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('tel', models.CharField(max_length=20, verbose_name='Tel phone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': '客户',
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
