# Generated by Django 2.1.3 on 2018-11-22 04:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    customer = apps.get_model("erp", "Customer")
    contract = apps.get_model("erp", "Contract")
    product = apps.get_model("erp", "Product")
    worker = apps.get_model("erp", "Worker")

    db_alias = schema_editor.connection.alias

    customer.objects.using(db_alias).bulk_create([
        customer(id=1, customer_name="辽宁千寻实业有限公司", customer_code="QX", customer_type=1),
        customer(id=2, customer_name="福建省三钢（集团）有限责任公司", customer_code="SG", customer_type=1),
        customer(id=3, customer_name="山西中科国际贸易有限公司", customer_code="YN", customer_type=2),
        customer(id=99, customer_name="通用", customer_code="GE", customer_type=99),
    ])

    contract.objects.using(db_alias).bulk_create([
        contract(id=1, contract_name="忠旺焙烧炉", customer_id=1),
        contract(id=2, contract_name="忠旺煅烧炉内管(一期)", customer_id=1),
        contract(id=3, contract_name="忠旺煅烧炉内管(二期)", customer_id=1),
        contract(id=4, contract_name="三钢三化焦化工程项目", customer_id=2),
        contract(id=5, contract_name="越南和发榕橘热回收炼焦项目一期", customer_id=3),
        contract(id=6, contract_name="越南和发榕橘热回收炼焦项目二期", customer_id=3),
    ])

    product.objects.using(db_alias).bulk_create([
        product(
            id=16513,
            product_name="莫来石质隔热耐火砖",
            product_model="1-65",
            use_for="焙烧炉外管",
            product_size="230*114*65",
            texture="CX-0.6",
            volume_weight=600,
            piece_weight=1.03,
            order_quantity=1600,
        )
    ])

    worker.objects.using(db_alias).bulk_create([
        worker(id=1, worker_name="马凤祥", worker_type="01"),
        worker(id=2, worker_name="马凤宜", worker_type="01"),
        worker(id=3, worker_name="于兴旺", worker_type="01"),
        worker(id=4, worker_name="王庆玉", worker_type="01"),
        worker(id=5, worker_name="汪永全", worker_type="01"),
        worker(id=6, worker_name="毛金国", worker_type="01"),
        worker(id=7, worker_name="陈兆祥", worker_type="02"),
        worker(id=8, worker_name="丁宝香", worker_type="02"),
        worker(id=9, worker_name="孙汉民", worker_type="02"),
        worker(id=10, worker_name="万东", worker_type="02"),
    ])


def reverse_func(apps, schema_editor):
    customer = apps.get_model("erp", "Customer")
    contract = apps.get_model("erp", "Contract")
    product = apps.get_model("erp", "Product")
    worker = apps.get_model("erp", "Worker")
    db_alias = schema_editor.connection.alias
    customer.objects.using(db_alias).delete()
    contract.objects.using(db_alias).delete()
    product.objects.using(db_alias).delete()
    worker.objects.using(db_alias).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
