# Generated by Django 2.1.3 on 2018-11-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20181121_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_name',
            new_name='contact',
        ),
    ]
