# Generated by Django 2.1.3 on 2018-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20181121_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(1, '国内'), (2, '国际'), (99, '一般')], default=1, null=0),
        ),
    ]
