# Generated by Django 2.1.3 on 2018-11-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=5, verbose_name='客户代码'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(1, '国内'), (2, '国际'), (99, '一般')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
    ]
