# Generated by Django 2.1.3 on 2018-11-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20181121_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('date_signed', models.DateField(verbose_name='签字日期')),
                ('delivery_date', models.DateField(verbose_name='交货日期')),
                ('contract_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='合同编号')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Customer')),
            ],
            options={
                'verbose_name_plural': '合同',
            },
        ),
    ]
