# Generated by Django 2.1.3 on 2018-11-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('erp', '0008_auto_20181121_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('product_model', models.CharField(max_length=20, verbose_name='产品型号')),
                ('use_for', models.CharField(blank=True, max_length=30, null=True, verbose_name='用途')),
                ('product_size', models.CharField(blank=True, max_length=25, null=True, verbose_name='产品尺寸')),
                ('texture', models.CharField(max_length=30, verbose_name='材质')),
                ('volume_weight', models.FloatField(blank=True, null=True, verbose_name='容重')),
                ('piece_weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('order_quantity', models.IntegerField(blank=True, null=True, verbose_name='订单数量')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_signed',
            field=models.DateField(blank=True, null=True, verbose_name='签字日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='交货日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Contract',
                                    verbose_name='所属合同'),
        ),
    ]
