# Generated by Django 2.1.3 on 2018-11-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('erp', '0009_auto_20181121_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contract',
        ),
        migrations.AddField(
            model_name='product',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Customer',
                                    verbose_name='所属客户'),
        ),
    ]
